package database;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseInitializer {

    private final ConnectionFactory connectionFactory;

    public DatabaseInitializer(ConnectionFactory connectionFactory) {
        this.connectionFactory = connectionFactory;
    }

    public void initialize() {
        try (Connection connection = connectionFactory.getConnection();
             Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS clientes (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        email VARCHAR(255) NOT NULL
                    )
                    """);

            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS produtos (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        preco DOUBLE PRECISION NOT NULL
                    )
                    """);

            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS pedidos (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        cliente_id BIGINT NOT NULL,
                        status VARCHAR(32) NOT NULL,
                        CONSTRAINT fk_pedidos_cliente
                            FOREIGN KEY (cliente_id) REFERENCES clientes(id)
                    )
                    """);

            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS itens_pedido (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        pedido_id BIGINT NOT NULL,
                        produto_id BIGINT NOT NULL,
                        quantidade INT NOT NULL,
                        CONSTRAINT fk_itens_pedido
                            FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE,
                        CONSTRAINT fk_itens_produto
                            FOREIGN KEY (produto_id) REFERENCES produtos(id)
                    )
                    """);
        } catch (SQLException e) {
            throw new IllegalStateException("Falha ao inicializar banco de dados.", e);
        }
    }
}
